parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    App\Application\Port\IContactRepository: '@App\Infrastructure\ForProduction\Repository\ContactRepository'
    App\Application\Port\IOrganizationRepository: '@App\Infrastructure\ForProduction\Repository\OrganizationRepository'
